- name: Create directory Vect
  become: true
  ansible.builtin.file: path=/vect state=directory
- name: Download Vector
  become: true
  ansible.builtin.get_url:
    url: "https://packages.timber.io/vector/0.21.0/vector-0.21.0-1.x86_64.rpm"
    dest: "/vect"
    mode: 0664
- name: Install Vector
  become: true
  ansible.builtin.yum:
    name: "/vect/vector-0.21.0-1.x86_64.rpm"
